# Generated by Django 4.2.5 on 2023-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_remove_usertoken_user_usertoken_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
