# Generated by Django 4.2.5 on 2023-09-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_remove_usertoken_username_usertoken_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
